---
- name: Instalando MariaDB
  hosts: webserver
  become: true
  tasks: 
    - name: Install MariaDB Packages
      ansible.builtin.apt:
        name: "{{ packages }}"
      vars: 
        packages: 
        - python3-pymysql
        - mariadb-server
    
    - name: Start MariaDB service
      ansible.builtin.service:
        name: mariadb
        state: started

    - name: Sets the root password
      community.mysql.mysql_user:
        name: root
        password: ansible
        state: present
        
    - name: Removes all anonymous user accounts
      community.mysql.mysql_user:
        name: ''
        host_all: yes
        state: absent
        login_user: root
        login_password: ansible

    - name: Removes the MySQL test database
      community.mysql.mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: ansible