---
- name: Instalando MariaDB
  hosts: webserver
  become: true
  tasks: 
    - name: Install MariaDB Packages
      ansible.builtin.apt:
        name: "{{ packages }}"
      vars: 
        packages: 
        - python3-pymysql
        - mariadb-server
      when: '"Ubuntu" in ansible_distribution'

    - name: Install MariaDB Packages
      ansible.builtin.dnf:
        name: "{{ packages }}"
      vars: 
        packages: 
        - python3-pymysql
        - mariadb-server
      when: '"Rocky" in ansible_distribution'
    
    - name: Start MariaDB service
      ansible.builtin.service:
        name: mariadb
        state: started

    - name: Sets the root password
      community.mysql.mysql_user:
        name: root
        password: abc123
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Removes all anonymous user accounts
      community.mysql.mysql_user:
        name: ''
        host_all: yes
        state: absent
        login_user: root
        login_password: abc123

    - name: Removes the MySQL test database
      community.mysql.mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: abc123

    - name: Create a new database with name 'bobdata'
      community.mysql.mysql_db:
        name: bobdata
        state: present

    