---
- name: Instalando Tomcat 10
  hosts: webserver
  become: true
  tasks: 
    - name: Install basic packages
      ansible.builtin.package:
        name: ['vim','aptitude','bash-completion','tmux','tree','htop','wget','unzip','curl','git']
        state: present
        update_cache: yes
      when: '"Ubuntu" in ansible_distribution'

    - name: Actualizando paquetes del sistema Ubuntu
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes
      when: '"Ubuntu" in ansible_distribution'

    - name: Add EPEL repository
      ansible.builtin.dnf:
        name: epel-release
        state: present
      when: '"Rocky" in ansible_distribution'

    - name: Install basic packages
      ansible.builtin.package:
        name: ['vim','bash-completion','tmux','tree','htop','wget','unzip','curl','git','gzip','tar']
        state: present
      when: '"Rocky" in ansible_distribution'

    - name: Actualizando paquetes del sistema Rocky
      ansible.builtin.dnf:
        update_only: yes
      when: '"Rocky" in ansible_distribution'
 
    - name: Creando usuario Tomcat
      ansible.builtin.user:
        name: tomcat
 
    - name: Creando Grupo de usuarios Tomcat
      ansible.builtin.group:
        name: tomcat
 
    - name: Instalando Java en sistema Ubuntu
      ansible.builtin.apt:
        name: default-jdk
        state: present
      when: '"Ubuntu" in ansible_distribution'

    - name: Instalando Java en sistema Rocky
      ansible.builtin.dnf:
        name: java-1.8.0-openjdk
        state: present
      when: '"Rocky" in ansible_distribution'
 
    - name: Creando directorio Tomcat, asignando dueño y permisos recursivos
      ansible.builtin.file:
        path: /opt/tomcat10
        owner: tomcat
        group: tomcat
        mode: 0755
        recurse: yes
        state: directory