---
- name: Instalando Tomcat 10
  hosts: webserver
  become: true
  tasks: 
    - name: Install basic packages
      package:
        name: ['vim','aptitude','bash-completion','tmux','tree','htop','wget','unzip','curl','git']
        state: present
        update_cache: yes
      when: '"Ubuntu" in ansible_distribution'

    - name: Actualizando paquetes del sistema Ubuntu
      apt:
        upgrade: yes
        update_cache: yes
      when: '"Ubuntu" in ansible_distribution'

    - name: Add EPEL repository
      yum:
        name: epel-release
        state: present
      when: '"Rocky" in ansible_distribution'

    - name: Install basic packages
      package:
        name: ['vim','bash-completion','tmux','tree','htop','wget','unzip','curl','git']
        state: present
      when: '"Rocky" in ansible_distribution'

    - name: Actualizando paquetes del sistema Rocky
      yum:
        update_only: yes
      when: '"Rocky" in ansible_distribution'
 
    - name: Creando usuario Tomcat
      user:
        name: tomcat
 
    - name: Creando Grupo de usuarios Tomcat
      group:
        name: tomcat
 
    - name: Instalando Java en sistema Ubuntu
      apt:
        name: default-jdk
        state: present
      when: '"Ubuntu" in ansible_distribution'

    - name: Instalando Java en sistema Rocky
      yum:
        name: java-1.8.0-openjdk
        state: present
      when: '"Rocky" in ansible_distribution'
 
    - name: Creando directorio Tomcat, asignando dueño y permisos recursivos
      file:
        path: /opt/tomcat10
        owner: tomcat
        group: tomcat
        mode: 0755
        recurse: yes
        state: directory
 
    - name: Descargando Tomcat 10 y descomprimiendo
      unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.23/bin/apache-tomcat-10.0.23.tar.gz
        dest: /opt/tomcat10
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Copiando servicio tomcat desde local hasta el nodo Ubuntu
      template:
        src: /home/ansible/taller-ort/tomcat.serviceubuntu
        dest: /etc/systemd/system/tomcat.service
        owner: root
        group: root
        mode: 0755
      when: '"Ubuntu" in ansible_distribution'

    - name: Copiando servicio tomcat desde local hasta el nodo Rocky
      template:
        src: /home/ansible/taller-ort/tomcat.serviceubuntu
        dest: /etc/systemd/system/tomcat.service
        owner: root
        group: root
        mode: 0755
      when: '"Rocky" in ansible_distribution'

    - name: Set UI access credentials
      template:
        src: tomcat-users.xml
        dest: /opt/tomcat10/conf/tomcat-users.xml
 
    - name: Start and Enable Tomcat 10 on sever
      systemd:
        name: tomcat
        state: started
        daemon_reload: true