---
- name: Install Apache Tomcat10 using ansible
  hosts: webserver
  become: true
  tasks:
    - name: Update the System Packages
      apt:
        upgrade: yes
        update_cache: yes
      when: '"Ubuntu" in ansible_distribution'

    - name: Instalar paquete httpd en redhat
      yum:
        update_only: yes
        update_cache: latest
      when: '"RedHat" in ansible_distribution'
 
    - name: Create a Tomcat User
      user:
        name: tomcat
 
    - name: Create a Tomcat Group
      group:
        name: tomcat
 
    - name: Install JAVA
      apt:
        name: default-jdk
        state: present
      when: '"Ubuntu" in ansible_distribution'

    - name: Install Java 8 CentOS
      yum:
        name: java-1.8.0-openjdk
        state: present
      when: '"RedHat" in ansible_distribution'
 
    - name: Create a Tomcat Directory
      file:
        path: /opt/tomcat10
        owner: tomcat
        group: tomcat
        mode: 755
        recurse: yes
 
    - name: download & unarchive tomcat10 
      unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.23/bin/apache-tomcat-10.0.23.tar.gz
        dest: /opt/tomcat10
        remote_src: yes
        extra_opts: [--strip-components=1]
 
    - name: Change ownership of tomcat directory
      file:
        path: /opt/tomcat10
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory

    - name: Copy Tomcat service from local to remote
      template:
        src: /home/ansible/taller-ort/tomcat.service.j2
        dest: /etc/systemd/system/tomcat.service
        owner: root
        group: root
        mode: 0755

    - name: Set UI access credentials
      template:
        src: tomcat-users.xml.j2
        dest: /opt/tomcat10/conf/tomcat-users.xml
      notify: restart tomcat
 
    - name: Start and Enable Tomcat 10 on sever
      systemd:
        name: tomcat
        state: started
        daemon_reload: true